name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Delete global.json files
      run: rm **/global.json && rm -f global.json
    - name: Restore dependencies
      run: cd Services/Roblox.Services && dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: cd ../Roblox.Services.UnitTest && dotnet test --no-build --verbosity normal
